image: debian:testing

.install: &install
  - apt-get update && apt-get install -qy ruby asciidoctor ruby-bundler ruby-rspec rubocop ruby-simplecov codespell ronn

tests:
  before_script: *install
  script:
    - rake test

manpages:
  before_script: *install
  script:
    - rake man

style:
  before_script: *install
  script:
    - rake style

codespell:
  before_script: *install
  script:
    - rake codespell
