inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - lib/chake.rb

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
